Repository FossifyOrg/Calendar, pull requests merged in 2025-05, with the labels that each got.

#578 chore(l10n): update translations
  app/src/main/res/values-ca/strings.xml
Labels: l10n

#581 ci: use conventional commit message in holiday generator
  .github/workflows/holiday-generator.yml
Labels: ci

#585 docs: remove local pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#597 ci: update holiday generator to use github app token
  .github/workflows/holiday-generator.yml
Labels: ci

#598 ci: generate github app token inside the same job
  .github/workflows/holiday-generator.yml
Labels: ci
